### ISSUE TITLE
turning off entity replacement?

### ISSUE THREAD

**Issue by zacwitte** [jsocol/bleach#147]
I'm getting a double encoding problem where bleach is encoding html entities like & on clean and then it's getting encoded again when markdown renders it. I'm using Misaka flask markdown package.

```python
>>> import bleach
>>> input_html = "Markdown [link](http://example.com?foo=bar&bar=foo)"
>>> output_html = bleach.clean(input_html)
>>> output_html
u'Markdown [link](http://example.com?foo=bar&amp;bar=foo)'
>>> import misaka as m
>>> print m.html(output_html)
<p>Markdown <a href="http://example.com?foo=bar&amp;amp;bar=foo">link</a></p>
```

notice the &amp;amp;

How do you suggest I get around this other than find/replace &amp; with &?

**Comment by jsocol** [comment]
I'd run bleach after markdown. These two things are never going to get along because markdown is defined as a superset of HTML, but it's a superset that bleach doesn't understand at all.

Entities are a bit of a problem right now (see #143, #130) but, IIRC, you should be fine if you swap the order.

Since markdown generates HTML, it's more correct and secure to run bleach on the result, anyway. You might also consider double-encoding entities like that a Misaka bug. I don't know if they would or not. Entities are hard to do correctly when you have multiple things parsing the markup.
